name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Add Environment Variables
      run: echo -e "TEST_A=${{ secrets.TEST_A }}\nSMTP_PORT=${{ secrets.SMTP_PORT }}\nSMTP_HOST=${{ secrets.SMTP_HOST }}\nSMTP_FROM_NAME=${{ secrets.SMTP_FROM_NAME }}\nSMTP_FROM_EMAIL=${{ secrets.SMTP_FROM_EMAIL }}\nSMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}\nSMTP_TEST_CONTENT=${{ secrets.SMTP_TEST_CONTENT }}\nSMTP_TEST_RECIPIENT_EMAIL=${{ secrets.SMTP_TEST_RECIPIENT_EMAIL }}\nSMTP_TEST_SUBJECT=${{ secrets.SMTP_TEST_SUBJECT }}\nSMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" > test-app/.env
    - name: Install dependencies
      run: npm ci
    - name: Install test application dependencies
      run: cd test-app && npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Boot servers up
      run: npm run actions &
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30