name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Link Sprint
      run: npm link
    - name: Link in project
      run: cd test-app && npm link sprint
    - name: Install test application dependencies
      run: cd test-app && npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Boot servers up
      run: npm run actions &
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
